name: Scheduled blog rebuild

on:
  schedule:
    - cron: "17 9 * * 1-5"   # Weekdays 09:17 UTC; adjust as desired
  workflow_dispatch:
  push:
    paths:
      - "content/blog/**"
      - "scripts/**"
      - "templates/**"
      - "index.html"
      - "blog.html"

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Build blog & homepage
        run: node scripts/build-blog.js

      - name: Commit generated pages (if changed)
        run: |
          git config user.name "kraftech-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(ci): scheduled rebuild of blog & homepage"
            git push
          else
            echo "No changes to commit."
          fi
